# -*- coding: utf-8 -*-
"""Ammonia Heat Pipe Calculations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gc_aOQuhigJXcjFRk4P8HbrGLYACVyfH
"""

from sympy import *
import numpy as np

# Initial Conditions!

# Water Stuff

WHeatCapacity = 4.18 # KJ/Kg*K, Specific heat capacity of Ammonia at 25*C

WHeatCapacity *= 1000 # J/Kg*K

WPressure = 0.5 # Atm (for now), pressure of ammonia gas inside the pipe

WMass = 18.01528 # g/mol, molar mass of ammonia

# Aluminum Stuff

AlDensity = 2710 # kg/m^3, density of aluminum!

AlDensity *= 1000 # now is g/m^3


# Pipe Stuff

TotalDistance = 100 # meters of pipe

Hollowradius = 9 # mm radius of pipe's inner cavity

InnerThickness = 4 # mm radius of inner pipe's thickness

EvacGapThickness = 10 # mm, thickness of the total evacuated gap in the pipe

SpiralNumber = 10 # number of spirals insulation should make around evacuated gap

SpiralThickness = 0.03 # mm Thickness of Aluminum Layers between each evacuated gap

OuterPipeThickness = 4 # mm, thickness of outer pipe around evacuated gap

InnerTemp = 25 # *C of ammonia inside pipe!

OuterTemp = -85 # *C estimated outside temp of mars

PipeInsulationConductivity = 0.003 # W/(m*k), Thermal conductivity of pipe's insulation


# Water Tank Stuff

TankTFlux = 0.126 # W/m^2 Thermal Flux of tank's insulation

TankExtArea = 2.8 # m^2, external area of water tank exposed to mars

TankHeatLoss = TankTFlux * TankExtArea # Power in watts being lost from the tanks




InnerRadius = Hollowradius + InnerThickness # mm radius of inner pipe's outer shell

InnerArea = 2 * pi * (InnerRadius/1000) * TotalDistance # m^2 Total External area of the inner pipe!

OuterRadius = InnerRadius + EvacGapThickness + OuterPipeThickness # mm, total radius of the pipe!


PipeHeatLoss = ((PipeInsulationConductivity * InnerArea)/EvacGapThickness) * (InnerTemp - OuterTemp) # W, heat transferred

TotalHeatNeeded = TankHeatLoss + PipeHeatLoss # Watts, J/s

WaterFlowRate = TotalHeatNeeded / (WHeatCapacity) # (J/s)/(J/Kg*K)  Kg/s, flow rate of ammonia needed to transfer the heat neeeded!

WaterFlowRate *= 1000 # conversion to g/s

# Next up need to figure out how fast the ammonia will be flowing with the pipes dimensions, as well as how much mass will be needed!

InternalXS = (Hollowradius/1000)**2 * pi # m^2, Cross sectional area of pipe's internal cavity!

# Velocity = Mass flow rate / (Ammonia's density * InternalXS)

WVol = (1 * 0.0821 * (InnerTemp + 273.15)) / WPressure # Liters, Using ideal gas law to get volume of ammonia!

WDensity = WMass / WVol # Grams per liter, density of the ammonia gas

WDensity *= 1000 # Converting from per Liter to per cubic meter! 1 g/l = 1000 g/m^3

WVelocity = (WaterFlowRate) / (WDensity * InternalXS) # g/s / (g/m^3 * m^2) = m/s


WTotalMass = InnerArea * (WDensity/1000) # grams, total mass of ammonia needed to fill the pipes at this specific density!





# need to calculate spiral with the number of spins across the two circles it is between and find that length
# use archimedian spiral equation!

ThetaMax = SpiralNumber * (2*pi) # radians, maximum value of theta that the function will go to!

theta, b = symbols('theta, b')

Rfun = InnerRadius + b * theta

Eq1 = Eq(InnerRadius + (b * ThetaMax), InnerRadius + EvacGapThickness) # use this equation to solve for b!

Soln = solve((Eq1), b)

b = Soln[0]

Rfun = InnerRadius + Soln[0] * theta # now that we have b, we wanna solve for the total length of the spiral!

SpiralLength = integrate(sqrt(Rfun**2 - diff(Rfun, theta)**2), (theta, 0, ThetaMax)) # in mm, total length of XS spiral of aluminum inside evacuated gap

InsulationXSArea = SpiralLength * SpiralThickness # mm^2, total area of aluminum layers in a cross section of pipe! This will get filled in in the following loop

InsulationXSArea /= 10**6 # m^2, converting the cross sectional area into square meters!

InsulationVolume = InsulationXSArea * TotalDistance # m^3, get total volume of aluminum by multiplying by distance of pipes!

AlMass = InsulationVolume * AlDensity # grams, Total mass of aluminum needed for pipes liners!


# need mass of inside and outside pipes! What material is it gonna be? just AL for now

InnerXSArea = (InnerRadius**2 - Hollowradius**2) * pi # mm^2, cross sectional area of inner pipe!

InnerXSArea /= 10**6 # m^2, converting to square meters

InnerVolume = InnerXSArea * TotalDistance # m^3

InnerPipeMass = InnerVolume * AlDensity


OuterXSArea = (OuterRadius**2 - (OuterRadius-OuterPipeThickness)**2) * pi # mm^2, cross sectional area of outer pipe!

OuterXSArea /= 10**6 # m^2, converting to square meters

OuterVolume = OuterXSArea * TotalDistance # m^3

OuterPipeMass = OuterVolume * AlDensity


TotalMass = WTotalMass + AlMass + InnerPipeMass + OuterPipeMass # total mass, in grams, needed for the pipes and ammonia!

WaterFlowRate = WaterFlowRate * (60**2)/1000 # converting g/s to kg/h


print(f"The total amount of heat needed is {N(TotalHeatNeeded)} watts")

print(f"The Water will have a flow rate of of {N(WaterFlowRate)} kg/h")

print(f"The Water will have a velocity of {N(WVelocity)} m/s")

print(f"The total mass of the Water is {N(WTotalMass)} grams")

print(f"The total mass of the Aluminum spiral is {N(AlMass)} grams")

print(f"The total mass of the Inner Pipe is {N(InnerPipeMass)} grams")

print(f"The total mass of the Outer Pipe is {N(OuterPipeMass)} grams")

print(f"The pipe's total radius is {OuterRadius} mm")

print(f"The total mass is {N(TotalMass)} grams")
print(f"The total mass is {N(TotalMass/1000)} Kilograms")

